var annotated_dup =
[
    [ "rd_sensor_configuration_t", "structrd__sensor__configuration__t.html", "structrd__sensor__configuration__t" ],
    [ "rd_sensor_data_bitfield_t", "structrd__sensor__data__bitfield__t.html", "structrd__sensor__data__bitfield__t" ],
    [ "rd_sensor_data_fields_t", "unionrd__sensor__data__fields__t.html", "unionrd__sensor__data__fields__t" ],
    [ "rd_sensor_data_t", "structrd__sensor__data__t.html", "structrd__sensor__data__t" ],
    [ "rd_sensor_t", "structrd__sensor__t.html", "structrd__sensor__t" ],
    [ "rd_test_gpio_cfg_t", "structrd__test__gpio__cfg__t.html", "structrd__test__gpio__cfg__t" ],
    [ "ri_adc_channel_config_t", "structri__adc__channel__config__t.html", "structri__adc__channel__config__t" ],
    [ "ri_adc_config_t", "structri__adc__config__t.html", "structri__adc__config__t" ],
    [ "ri_adc_get_data_t", "structri__adc__get__data__t.html", "structri__adc__get__data__t" ],
    [ "ri_adc_pin_config_t", "structri__adc__pin__config__t.html", "structri__adc__pin__config__t" ],
    [ "ri_adc_pins_config_t", "structri__adc__pins__config__t.html", "structri__adc__pins__config__t" ],
    [ "ri_adv_scan_t", "structri__adv__scan__t.html", "structri__adv__scan__t" ],
    [ "ri_comm_channel_t", "structri__comm__channel__t.html", "structri__comm__channel__t" ],
    [ "ri_comm_dis_init_t", "structri__comm__dis__init__t.html", "structri__comm__dis__init__t" ],
    [ "ri_comm_message_t", "structri__comm__message__t.html", "structri__comm__message__t" ],
    [ "ri_gpio_evt_t", "structri__gpio__evt__t.html", "structri__gpio__evt__t" ],
    [ "ri_i2c_init_config_t", "structri__i2c__init__config__t.html", "structri__i2c__init__config__t" ],
    [ "ri_lis2dh12_dev", "structri__lis2dh12__dev.html", "structri__lis2dh12__dev" ],
    [ "ri_power_regulators_t", "structri__power__regulators__t.html", "structri__power__regulators__t" ],
    [ "ri_radio_channels_t", "structri__radio__channels__t.html", "structri__radio__channels__t" ],
    [ "ri_spi_init_config_t", "structri__spi__init__config__t.html", "structri__spi__init__config__t" ],
    [ "ri_uart_init_t", "structri__uart__init__t.html", "structri__uart__init__t" ],
    [ "rt_adv_init_t", "structrt__adv__init__t.html", "structrt__adv__init__t" ],
    [ "rt_button_init_t", "structrt__button__init__t.html", "structrt__button__init__t" ],
    [ "rt_sensor_ctx_t", "structrt__sensor__ctx__t.html", "structrt__sensor__ctx__t" ],
    [ "ruuvi_interface_uart_init_config_t", "structruuvi__interface__uart__init__config__t.html", "structruuvi__interface__uart__init__config__t" ]
];