var topics =
[
    [ "Driver tets", "group__test__driver.html", "group__test__driver" ],
    [ "Atomic functions", "group___atomic.html", null ],
    [ "Radio operations.", "group___radio.html", "group___radio" ],
    [ "Crypto functions", "group___crypto.html", "group___crypto" ],
    [ "ADC_NTC Interface", "group___a_d_c___n_t_c.html", null ],
    [ "ADC_PHOTO Interface", "group___a_d_c___p_h_o_t_o.html", null ],
    [ "BME280 Inteface", "group___b_m_e280.html", null ],
    [ "Environmental sensing", "group___environmental.html", "group___environmental" ],
    [ "Environmental sensing with MCU", "group___e_n_v_i_r_o_n_m_e_n_t_a_l___m_c_u.html", "group___e_n_v_i_r_o_n_m_e_n_t_a_l___m_c_u" ],
    [ "SHTCX Interface", "group___s_h_t_c_x.html", "group___s_h_t_c_x" ],
    [ "Flash storage.", "group___flash.html", "group___flash" ],
    [ "GPIO functions", "group___g_p_i_o.html", "group___g_p_i_o" ],
    [ "I2C functions", "group___i2_c.html", "group___i2_c" ],
    [ "Logging functions", "group___log.html", "group___log" ],
    [ "CPU power", "group___power.html", null ],
    [ "RTC functions", "group___r_t_c.html", null ],
    [ "Interface for scheduling tasks to be executed later.", "group__scheduler.html", "group__scheduler" ],
    [ "SPI functions", "group___s_p_i.html", "group___s_p_i" ],
    [ "Interface for timing tasks to be exeuted later.", "group__timer.html", "group__timer" ],
    [ "UART functions", "group___u_a_r_t.html", "group___u_a_r_t" ],
    [ "Watchdog timer functions", "group___watchdog.html", null ],
    [ "Yield and delay functions", "group___yield.html", null ],
    [ "Error reporting and handling", "group___error.html", "group___error" ],
    [ "Common sensor interface", "group___sensor.html", "group___sensor" ],
    [ "Sending and receiving data.", "group__communication__tasks.html", "group__communication__tasks" ],
    [ "Peripheral tasks", "group__peripheral__tasks.html", "group__peripheral__tasks" ],
    [ "GPIO tasks", "group__gpio__tasks.html", null ],
    [ "Interacting with outside world", "group__actuator__tasks.html", null ],
    [ "LED tasks", "group__led__tasks.html", null ],
    [ "NFC tasks", "group__nfc__tasks.html", null ],
    [ "Sensor tasks", "group__sensor__tasks.html", null ],
    [ "Sensor", "group__sensor.html", "group__sensor" ],
    [ "BLE", "group___b_l_e.html", "group___b_l_e" ],
    [ "NFC", "group___n_f_c.html", "group___n_f_c" ],
    [ "Power", "group__power.html", "group__power" ],
    [ "Acceleration", "group___acceleration.html", "group___acceleration" ],
    [ "ADC", "group___a_d_c.html", null ],
    [ "ADC tasks", "group__adc__tasks.html", "group__adc__tasks" ],
    [ "Button tasks", "group__button__tasks.html", null ]
];